engage/engage/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from tag.views import index
admin.autodiscover()

handler404 = 'tag.views.error_page'
handler500 = 'tag.views.error_page'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'engage.views.home', name='home'),
    # url(r'^engage/', include('engage.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', index, name="index"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tag/', include('tag.urls',namespace='tag')),
)

engage/tag/urls.py
from django.conf.urls import patterns, include, url
import views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'engage.views.home', name='home'),
    # url(r'^engage/', include('engage.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.tag_index, name='tag_index'),
    url(r'^posts/$', views.posts, name='posts'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signout/$', views.signout, name='signout'),
    url(r'^create-post/$', views.create_post, name='create-post'),
    url(r'^show-mentions/$', views.show_posts, name='show-post'),
    url(r'^my-posts/$', views.my_posts, name='my-posts'),  

)

engage/permission_backend_nonrel/models.py
from django.contrib.auth.models import User, Group
from django.db import models

from djangotoolbox.fields import ListField


class UserPermissionList(models.Model):
    user = models.ForeignKey(User)

    permission_list = ListField(models.CharField(max_length=64))
    permission_fk_list = ListField(models.CharField(max_length=32))

    group_fk_list = ListField(models.CharField(max_length=32))


class GroupPermissionList(models.Model):
    group = models.ForeignKey(Group)
    permission_list = ListField(models.CharField(max_length=64))
    permission_fk_list = ListField(models.CharField(max_length=32))

engage/tag/models.py
from django.db import models
from django.contrib.auth.models import User
from djangotoolbox.fields import ListField
from django_mongodb_engine.contrib import MongoDBManager


# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User, unique=True, null=True)
	friend_list = ListField()
	full_name = models.CharField(max_length=200)

class Posts(models.Model):
	post = models.CharField(max_length=1200)
	created_by = models.CharField(max_length=200)
	mentions = ListField()

engage/tag/views.py
# Create your views here.

from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from django.contrib.auth import login, logout
from tag.models import *
from django.contrib.auth.models import User
import json
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from pymongo import	MongoClient
client = MongoClient()
db = client.engage

# main page
def index(request):
	return redirect('/tag/')

# tag application index / login page
def tag_index(request):
	context = RequestContext(request,{})
	if request.user.is_authenticated():
		return redirect('/tag/posts')
	else:
		return render_to_response('index.html', context_instance=context)

# signup function when signup is clicked
def signup(request):
	username = request.POST.get('email','')
	first_name = request.POST.get('first_name','')
	last_name = request.POST.get('last_name','')
	friend_list = request.POST.getlist('friend_list[]','')

	exists = User.objects.filter(username__exact=username).exists()
	
	if exists:
		user = User.objects.get(username=username)
		user_profile = UserProfile.objects.get(user_id=user.pk)
		user_profile.full_name = user.first_name+ " " + user.last_name
		user_profile.friend_list = friend_list
		user_profile.save()
	else:
		user = User.objects.create_user(username, username)
		user.first_name = first_name
		user.last_name = last_name
		user.save()

		full_name = user.first_name+ " " + user.last_name
		user_profile_exists = UserProfile.objects.filter(full_name=full_name).exists()

		if user_profile_exists:
			user_profile = UserProfile.objects.get(full_name=full_name)
			user_profile.user_id = user.pk
		else:
			user_profile = UserProfile(user_id=user.pk)

		user_profile.full_name = full_name
		user_profile.friend_list = friend_list
		user_profile.save()

	if request.user.is_authenticated():
		return HttpResponse(json.dumps({'url':'/tag/posts'}),mimetype='application/json')
		
	user.backend = 'django.contrib.auth.backends.ModelBackend'
	login(request,user)
	return HttpResponse(json.dumps({'url':'/tag/posts'}),mimetype='application/json')

# post page to make posts
def posts(request):
	email = request.user.email
	user = User.objects.get(email=email)
	user_profile = UserProfile.objects.get(user_id=user.pk)
	
	friends = json.dumps(user_profile.friend_list)

	context = RequestContext(request,{'friends':friends})
	return render_to_response('posts.html', context_instance=context)

# signout function when signout is called
def signout(request):
	logout(request)
	return redirect('/tag')

# to create posts
def create_post(request):
	if request.method == "POST":
		user = User.objects.get(email = request.user.email)
		user_profile_id = UserProfile.objects.get(user_id=user.pk).id

		mentions = request.POST.getlist('mentions[]','')
		post = request.POST.get('post','')

		post = Posts(post=post, created_by=user_profile_id)
		mentions_list = []

		print mentions
		for mention in mentions:
			exists = UserProfile.objects.filter(full_name=mention).exists()
			if exists:
				## fetch
				user_profile = UserProfile.objects.get(full_name=mention)
			else:
				## create
				user_profile = UserProfile(full_name = mention)
				user_profile.save()
			mentions_list.append(user_profile.id)

		post.mentions = mentions_list
		post.save()

		return HttpResponse(json.dumps({'added':True}), mimetype='application/json')
	else:
		return HttpResponse(json.dumps({'message':'invalid call to url has been made'}), 
										mimetype='application/json')


# to show mentioned posts
def show_posts(request):
	user = User.objects.get(email = request.user.email)
	user_profile_id = UserProfile.objects.get(user_id=user.pk).id

	results = Posts.objects.filter(mentions=user_profile_id).values('post')

	context = RequestContext(request, {'mentions':results, 'title':'Mentioned posts'})
	return render_to_response('show-mentions.html',context)

# to show user's posts
def my_posts(request):
	user = User.objects.get(email = request.user.email)
	user_profile_id = UserProfile.objects.get(user_id=user.pk).id
	results = Posts.objects.filter(created_by=user_profile_id).values('post')

	context = RequestContext(request, {'mentions':results, 'title':'My posts'})
	return render_to_response('show-mentions.html',context)


def error_page(request):
	context = RequestContext(request, {})
	return render_to_response('error.html',context)

engage/tag/templates/backup.html
<!DOCTYPE html>
<html>
<head>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
<title>Home | Sweet Home</title>
<meta charset="UTF-8">

<style type="text/css">
  .fb-login{
      background: #3853a4;
      color:white;
      font-size: 1em;
      padding:0.8em;
      border-radius: 0.4em;
      border:none;
      font-family: 'Roboto Condensed', sans-serif;
      cursor: pointer;
  }

  .fb-login i{
    font-size: 1.5em;
    padding-right: 0.3em;
    vertical-align: middle;
  }

  .center-text{
    text-align: center;
  }

  .main-content{
    margin-top: 25%;
  }

  body{
    background:url('http://i.telegraph.co.uk/multimedia/archive/02220/beatles-abbey-road_2220576b.jpg');
    font-family: 'Roboto Condensed', sans-serif;
    background-size: cover;

  }

</style>
</head>
<body>
<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  var fbData = {};

  function login() {
     FB.login(function(response) {
        if (response.status === 'connected') {
        // Logged into your app and Facebook.


        FB.api('/me?fields=email,first_name,last_name',function(response){
          fbData["email"] = response.email;
          fbData["first_name"] = response.first_name;
          fbData["last_name"] = response.last_name;
          fbData["csrfmiddlewaretoken"] = '{{csrf_token}}'
        });

        FB.api('/me/friends', function(response){
          total_count = response.summary.total_count;        
          FB.api('/me/taggable_friends?limit='+total_count, function(response){
            console.log(response);
            fbData["friend_list"] = response.data.map(function(a){ return a.name; });

            $.post("{% url "tag:signup" %}", fbData, function(response){
         
                window.location.href=response.url;

            });
            
          });
        });
      } 
     }, {scope: 'public_profile,email,user_friends'});
  }
  
  window.fbAsyncInit = function() {
  FB.init({
    appId      : '1728957830668724',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.2' // use version 2.2
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  // FB.getLoginStatus(function(response) {
  //   statusChangeCallback(response);
  // });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->

<!-- <button class="fb_login" onclick="checkLoginState();">Login with Facebook</button>  -->

<!-- <fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button> -->

<div class="main-content center-text">


  <button class="fb-login"><i class="fa fa-facebook"></i>Login with Facebook</button> 

</div>


<div id="status">
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-beta1/jquery.min.js"></script>
<script type="text/javascript">

$(".fb-login").click(function(){
   // checkLoginState();
   login();
})

</script>
</body>
</html>

engage/tag/templates/error.html
<html>
<head>
	<title>
		Oops...
	</title>
	<link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
	<link rel="stylesheet" href="{{STATIC_URL}}nav.css">

	<style type="text/css">

	.center-text{
	    text-align: center;
	}

	.medium-font-size{
		font-size: 2em;
	}

	.large-font-size{
		font-size: 5em;
	}

	.roboto{	    
	    font-family: 'Roboto Condensed', sans-serif;
	}

	.main-content{
	    margin-top: 10%;
	}

	</style>
</head>
<body>
	
	<div class="center-text roboto medium-font-size main-content">
		Oops..Page does not exist, something went wrong.<br/>
		<div class="large-font-size">
			<i class="fa fa-frown-o"></i>
		</div>
		Go <a href="/tag">home</a>.
	</div>

</body>

</html>

engage/tag/templates/index.html
<!DOCTYPE html>
<html>
<head>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
<title>Home | Sweet Home</title>
<meta charset="UTF-8">

<style type="text/css">
  .fb-login{
      background: #3853a4;
      color:white;
      font-size: 1em;
      padding:0.8em;
      border-radius: 0.4em;
      border:none;
      font-family: 'Roboto Condensed', sans-serif;
      cursor: pointer;
  }

  .fb-login i{
    font-size: 1.5em;
    padding-right: 0.3em;
    vertical-align: middle;
  }

  .center-text{
    text-align: center;
  }

  .main-content{
    margin-top: 25%;
  }

  body{
    background:url('http://i.telegraph.co.uk/multimedia/archive/02220/beatles-abbey-road_2220576b.jpg');
    font-family: 'Roboto Condensed', sans-serif;
    background-size: cover;

  }

</style>
</head>
<body>
{% include "logout.html" %}

<div class="main-content center-text">

  <button class="fb-login"><i class="fa fa-facebook"></i>Login with Facebook</button> 

</div>


<div id="status">
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-beta1/jquery.min.js"></script>
<script type="text/javascript">

$(".fb-login").click(function(){
   // checkLoginState();
   login();
})

</script>
</body>
</html>

engage/tag/templates/logout.html
<script>

  var fbData = {};

  function login() {
     FB.login(function(response) {
        if (response.status === 'connected') {
        // Logged into your app and Facebook.
        FB.api('/me?fields=email,first_name,last_name',function(response){
          fbData["email"] = response.email;
          fbData["first_name"] = response.first_name;
          fbData["last_name"] = response.last_name;
          fbData["csrfmiddlewaretoken"] = '{{csrf_token}}'
        });

        FB.api('/me/friends', function(response){
          total_count = response.summary.total_count;        
          FB.api('/me/taggable_friends?limit='+total_count, function(response){
            fbData["friend_list"] = response.data.map(function(a){ return a.name; });

            $.post("{% url "tag:signup" %}", fbData, function(response){
         
                window.location=response.url;

            });
            
          });
        });
      } 
     }, {scope: 'public_profile,email,user_friends'});
  }
  
  window.fbAsyncInit = function() {
  FB.init({
    appId      : '1728957830668724',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.2' // use version 2.2
  });
};

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));


  function logout(){
	FB.getLoginStatus(function(response) {
        if (response && response.status === 'connected') {
            FB.logout(function(response) {
                window.location = "{% url "tag:signout" %}";
            });
        }
    });
	 
}

</script>

engage/tag/templates/navbar.html
{% if user.is_authenticated %}
<header>
	<nav id="top-navigation">
		<ul>
			<li> Hi {{ user.first_name }}  <i class="fa fa-angle-double-right"></i></li>
			<li><a href="{% url "tag:posts" %}">Post</a></li>
			<li><a href="{% url "tag:show-post" %}">Show mentioned posts</a></li>
			<li><a href="{% url "tag:my-posts" %}">Show my posts</a></li>
			<li><a href="#" onclick="logout()">Logout</a></li>
		</ul>
	</nav>
</header>

{% endif %}

engage/tag/templates/posts.html
<html>
{% load staticfiles %}
<head>
	<title>
		Posts
	</title>
	<link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
	<link rel="stylesheet" href="{{STATIC_URL}}nav.css">
	<link rel="stylesheet" href="{{STATIC_URL}}jquery.textcomplete.css">
	{% include "logout.html" %}
  	<style type="text/css">
  	
	  .center-text{
	    text-align: center;
	  }

	  .main-content{
	    margin-top: 10%;
	  }

	  .roboto{	    
	    font-family: 'Roboto Condensed', sans-serif;
	  }

	  .block-element{
	  	display: block;
	  	margin: 2em 0;
	  }

	  body{
	  	background-color: #C2185B;
	  }

	  .styled-btn{
	      background: black;
	      color:white;
	      font-size: 1em;
	      padding:0.8em;
	      border-radius: 0.4em;
	      border:none;
	      font-family: 'Roboto Condensed', sans-serif;
	      cursor: pointer;
	      vertical-align: middle;
	  }

	  .results{
	  	color:white;
	  }

  	</style>

  	
</head>

<body>
	{% include 'navbar.html' %}

	<div class="main-content roboto">
		<span class="block-element"> Post anything that you want, use @ to auto-suggest from your friend list... </span>
		<textarea class="mention" rows="10" cols="50"></textarea>
		<input type="submit" value="Submit" class="styled-btn block-element submit-form"></input>
		<!-- <input id="tag"> -->
		<span class="block-element results"></span>
	</div>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-beta1/jquery.min.js"></script>
	<script src="{{STATIC_URL}}jquery.overlay.js"></script>
	<script src="{{STATIC_URL}}auto-complete.js"></script>

	<script type="text/javascript">
		var mentions = [];
		$('.mention').textcomplete([
	    { // html 
	        mentions: {{friends|safe}} ,
	        match: /\B@(\w*)$/,
	        search: function (term, callback) {
	            callback($.map(this.mentions, function (mention) {
	                return mention.indexOf(term) === 0 ? mention : null;
	            }));
	        },
	        index: 1,
	        replace: function (mention) {
	        	mentions.push(mention);
	            return '@'+mention+' ';
	        }
	    }
		]);

		$('.mention').click(function(){
			$(".results").empty();
		})

		$(".submit-form").click(function(){

			$(".results").empty();
			var post = $(".mention").val();
			var friendsMentioned = $.unique(mentions);

			for(var i=0;i<friendsMentioned.length;i++){
				if (! (post.indexOf(friendsMentioned[i]) > -1) )
				{
					friendsMentioned = jQuery.grep(friendsMentioned, function(value) {
					  return value != friendsMentioned[i];
					});
				}

			}
			
			postData = {
				'post':post,
				'mentions':friendsMentioned,
				'csrfmiddlewaretoken':'{{csrf_token}}'
			}
			$.post("{% url "tag:create-post" %}",postData,function(response){

				if (response.added){
					$(".results").append("Your post has been successfully made..");
					$(".mention").val("");
				}
				else{
					$(".results").append("Sorry..your post couldn't be submitted...");
				}

				mentions = [];

			});
		});
		
	</script>


	

</body>
</html>

engage/tag/templates/show-mentions.html
<html>
{% load staticfiles %}
<head>
	<title>
		Mentioned posts
	</title>
	<link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
	<link rel="stylesheet" href="{{STATIC_URL}}nav.css">
	{% include "logout.html" %}
  	<style type="text/css">
  	
	  .center-text{
	    text-align: center;
	  }

	  .main-content{
	    margin-top: 5%;
	  }

	  .roboto{	    
	    font-family: 'Roboto Condensed', sans-serif;
	  }

	  .block-element{
	  	display: block;
	  	margin: 2em 0;
	  }

	  body{
	  	background-color: #C2185B;
	  }

	  .post-headline{
	  	font-size: 2em;
	  	text-align: center;
	  }

	  hr{
	  	width: 20%;
	    background: black;
	    border: none;
	    outline: none;
	    height: 0.1em;
	  }

  	</style>
  	
</head>

<body>

	{% include 'navbar.html' %}

	<div class="main-content roboto">
	
		<div class="post-headline">
			<hr>
			<span> {{ title }}</span>
			<hr>
		</div>

		{% if mentions %}
			{% for mention in mentions reversed %}
			<textarea disabled class="block-element" rows="7" cols="50">{{ mention.post }}</textarea>
			{% endfor %}
		{% else %}
			<span class="center-text">
				Sorry, you do not have any posts <i class="fa fa-frown-o"></i>
			</span>
		{% endif %}
	</div>

</body>
</html>